export const M = {
  CHANGE_SEARCH_STR: 'CHANGE_SEARCH_STR',
  CHANGE_SEARCH_RESULTS: 'CHANGE_SEARCH_RESULTS',
  CHANGE_LOCATION: 'CHANGE_LOCATION',
  OPEN_PLAYER: 'OPEN_PLAYER',
  CHANGE_PLAYER_SIZE: 'CHANGE_PLAYER_SIZE'
}
